channels:
- conda-forge
- defaults
dependencies:
- appdirs
- boto3
- click
- cryptography
- flask
- h5py
- ipython
- mamba>0.21
- matplotlib
- minio
- networkx<2.8.3
- numpy
- otumat
- pandas
- pip>=22.0
- plotly
- plotnine
- polars
- pydot
- pymysql
- pyparsing
- python==3.9.*
- pyyaml
- scipy
- seaborn
- tomli
- tqdm
- urllib3
- pip:
  - datajoint-utilities @ git+https://github.com/datajoint-company/datajoint-utilities
  - datajoint>=0.13.7
  - dj-wft-cim @ git+https://github.com/dj-sciops/wt-causality-in-motion
  - djsciops
name: brain_lab
