default_language_version:
  python: python{{cookiecutter.python_version}}
# files: "^(tests|src\/{{cookiecutter.__pkg_import_name}})\/.*$"
exclude: "^$"
default_stages: [commit, push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-case-conflict
      - id: detect-private-key
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: name-tests-test
        args: ['--django']
      - id: check-added-large-files
        args: ["--maxkb=5000"]
      - id: end-of-file-fixer
        exclude: LICENSE
      - id: mixed-line-ending
        args: ["--fix=lf"] # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows

  # run black code formatter on python files
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - "--config"
          - "./pyproject.toml"

  # run isort on python files to sort imports
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args:
          - "--settings-file"
          - "./pyproject.toml"

    # Run black on python code blocks in documentation files.
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black]

  # strip out metadata for notebooks
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
