# Run various tests using pytest{% raw %}
name: run-tests

on:
  workflow_run:
    workflows:
      - pre-commit
    types:
      - completed
    branches:
      - main

jobs:
  run_tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10"]
        exclude:
          - os: macos-latest
            python-version: "3.8"
          - os: windows-latest
            python-version: "3.8"

    defaults:
      run:
        shell: bash

    steps:
      - name: ğŸ›ï¸  Checkout repository
        id: check-repo
        uses: actions/checkout@v3

      - name: ğŸ  Install python and nox
        uses: ./.github/actions/nox-python
        with:
          py_ver: ${{ matrix.python-version }}
          key_append: test-${{ matrix.python-version }}

      - name: ğŸ  Build all package dependencies and run main cli
        run: nox --force-python ${{ matrix.python-version }} -s main_cli -v --non-interactive

      - name: ğŸ  Run pytest
        run: nox --force-python ${{ matrix.python-version }} -s pytest -v --non-interactive
#{% endraw %}
