# Run various tests
name: run-tests
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸  Checkout repository
        id: check-repo
        uses: actions/checkout@v3

      - name: ğŸ  Use Python
        id: use-python
        uses: actions/setup-python@v3
        with:
          python-version: "{{cookiecutter.python_version}}"

      - name: ğŸ  Install Nox
        id: install-nox
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install nox

      - name: ğŸ  Run pytest
        run: nox --non-interactive -v -s pytest
