default_language_version:
  python: python3.10
# files: "^(tests|src\/basic_package)\/.*$"
exclude: "^$"
default_stages: [commit, push]
repos:
  # for debugging hook input arguments
  - repo: meta
    hooks:
      - id: identity
        exclude: (devcontainer\.json|\.code-workspace)$

  # out-of-the-box hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-case-conflict
      - id: detect-private-key
      - id: check-json
        exclude: (devcontainer\.json|\.code-workspace)$
      - id: check-toml
      - id: check-yaml
      - id: name-tests-test
        args: ["--django"]
      - id: check-added-large-files
        args: ["--maxkb=25000"]
      - id: end-of-file-fixer
        exclude: LICENSE
      - id: mixed-line-ending
        args: ["--fix=lf"] # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows

  # run black code formatter on python files
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args:
          - "--config"
          - "./pyproject.toml"

  # run isort on python files to sort imports
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - "--settings-file"
          - "./pyproject.toml"

  # run black on python code blocks in documentation files.
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black]

  # strip out metadata for notebooks
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout

  # python linting
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: (^tests/(integration/fixtures|unit/data)/)|(notebooks/)
        args:
          # making isort line length compatible with black
          # https://flake8.pycqa.org/en/latest/user/error-codes.html
          - "--max-line-length=88"
          - "--max-complexity=18"
          - "--select=B,C,E,F,W,T4,B9"
          - "--ignore=E203,E266,E501,W503,F403,F401,E402,E741"
