# Run various tests{% raw %}
name: run-tests
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›ï¸  Checkout repository
        id: check-repo
        uses: actions/checkout@v3

      - name: ğŸ—„ï¸  Nox venv cache
        id: cache_nox
        uses: actions/cache@v2
        with:
          path: .nox
          key: ${{ runner.os }}-nox-pythons

      - name: ğŸ  Setup nox
        uses: excitedleigh/setup-nox@v2

      - name: ğŸ  Run pytest
        run: nox --non-interactive -v -s pytest
#{% endraw %}
