name: run-ci-jobs

on:
  push:
    branches: ["main"]

jobs:
  get_tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create a tag
        uses: mathieudutour/github-tag-action@v6.0
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          create_annotated_tag: false
          fetch_all_tags: true

  generate_workflow_content:
    runs-on: ubuntu-latest
    needs: get_tag
    if: |
      always() &&
      (needs.get_tag.result == 'success') &&
      (github.ref_name == 'main') &&
      (github.ref_type == 'branch')
    steps:
      - name: Checkout Repository for Local Action
        uses: actions/checkout@v3

      - name: Generate Content from 'workflow-example' Template
        id: bake-cookies
        uses: ./.github/actions/bake-cookies
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: workflow-example
          folder: workflow_name
          new_tag: ${{ needs.get_tag.outputs.new_tag }}
    outputs:
      artifact: ${{ steps.bake-cookies.outputs.artifact }}

  generate_flit_content:
    runs-on: ubuntu-latest
    needs: [get_tag, generate_workflow_content]
    if: |
      always() &&
      (needs.get_tag.result == 'success') &&
      (needs.generate_workflow_content.result == 'success') &&
      (github.ref_name == 'main') &&
      (github.ref_type == 'branch')
    steps:
      - name: Checkout Repository for Local Action
        uses: actions/checkout@v3

      - name: Generate Content from 'flit' Template
        id: bake-cookies
        uses: ./.github/actions/bake-cookies
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: flit
          folder: o-science-institute_w-neuro-lab
          cookiecutter_pkg: git+https://github.com/cookiecutter/cookiecutter tomli
          new_tag: ${{ needs.get_tag.outputs.new_tag }}
    outputs:
      artifact: ${{ steps.bake-cookies.outputs.artifact }}

  generate_sciops_cicd_content:
    runs-on: ubuntu-latest
    needs: [get_tag, generate_flit_content]
    if: |
      always() &&
      (needs.get_tag.result == 'success') &&
      (needs.generate_flit_content.result == 'success') &&
      (github.ref_name == 'main') &&
      (github.ref_type == 'branch')
    steps:
      - name: Checkout Repository for Local Action
        uses: actions/checkout@v3

      - name: Generate Content from 'sciops-cicd' Template
        id: bake-cookies
        uses: ./.github/actions/bake-cookies
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: sciops-cicd
          folder: .github
          new_tag: ${{ needs.get_tag.outputs.new_tag }}
    outputs:
      artifact: ${{ steps.bake-cookies.outputs.artifact }}

  generate_u24_cicd_content:
    runs-on: ubuntu-latest
    needs: [get_tag, generate_sciops_cicd_content]
    if: |
      always() &&
      (needs.get_tag.result == 'success') &&
      (needs.generate_sciops_cicd_content.result == 'success') &&
      (github.ref_name == 'main') &&
      (github.ref_type == 'branch')
    steps:
      - name: Checkout Repository for Local Action
        uses: actions/checkout@v3

      - name: Generate Content from 'u24-cicd' Template
        id: bake-cookies
        uses: ./.github/actions/bake-cookies
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: u24-cicd
          folder: .github
          new_tag: ${{ needs.get_tag.outputs.new_tag }}
    outputs:
      artifact: ${{ steps.bake-cookies.outputs.artifact }}

  make_release:
    runs-on: ubuntu-latest
    needs:
      [
        get_tag,
        generate_flit_content,
        generate_workflow_content,
        generate_sciops_cicd_content,
        generate_u24_cicd_content,
      ]
    if: |
      always() &&
      (needs.get_tag.result == 'success') &&
      (needs.generate_u24_cicd_content.result == 'success')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Downloading 'flit' Artifact Content
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.generate_flit_content.outputs.artifact }}
          path: ${{ needs.generate_flit_content.outputs.artifact }}

      - name: Downloading 'workflow' Artifact Content
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.generate_workflow_content.outputs.artifact }}
          path: ${{ needs.generate_workflow_content.outputs.artifact }}

      - name: Downloading 'sciops_cicd_content' Artifact Content
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.generate_sciops_cicd_content.outputs.artifact }}
          path: ${{ needs.generate_sciops_cicd_content.outputs.artifact }}

      - name: Downloading 'u24_cicd_content' Artifact Content
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.generate_u24_cicd_content.outputs.artifact }}
          path: ${{ needs.generate_u24_cicd_content.outputs.artifact }}

      - run: |
          tar -zcf ${{ needs.generate_workflow_content.outputs.artifact }}.tar.gz ${{ needs.generate_workflow_content.outputs.artifact }}
          tar -zcf ${{ needs.generate_flit_content.outputs.artifact }}.tar.gz ${{ needs.generate_flit_content.outputs.artifact }}
          tar -zcf ${{ needs.generate_sciops_cicd_content.outputs.artifact }}.tar.gz ${{ needs.generate_sciops_cicd_content.outputs.artifact }}
          tar -zcf ${{ needs.generate_u24_cicd_content.outputs.artifact }}.tar.gz ${{ needs.generate_u24_cicd_content.outputs.artifact }}

      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.get_tag.outputs.new_tag }}
          name: ${{ github.ref_name }}-release ${{ needs.get_tag.outputs.new_tag }}
          body: ${{ needs.get_tag.outputs.changelog }}
          allowUpdates: true
          generateReleaseNotes: true
          artifacts: |
            ${{ needs.generate_workflow_content.outputs.artifact }}.tar.gz
            ${{ needs.generate_flit_content.outputs.artifact }}.tar.gz
            ${{ needs.generate_sciops_cicd_content.outputs.artifact }}.tar.gz
            ${{ needs.generate_u24_cicd_content.outputs.artifact }}.tar.gz
